project_id = "jvbotyzrgpxewwvjlnef"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.create-student-user]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.send-password-setup]
verify_jwt = false

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false
